# Generated by Django 5.2.6 on 2025-10-02 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_mechanic_booking_pickup_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('experience', models.PositiveIntegerField(verbose_name='ประสบการณ์ (ปี)')),
                ('shop_name', models.CharField(max_length=100, verbose_name='ชื่อร้าน/อู่')),
                ('shop_address', models.CharField(max_length=255, verbose_name='ที่อยู่ร้าน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
