# Generated by Django 5.2.6 on 2025-10-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mechanicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='อาการรถ (จองคิว)'),
        ),
        migrations.AddField(
            model_name='motorbike',
            name='symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='อาการรถ (default)'),
        ),
        migrations.AddField(
            model_name='motorbike',
            name='vehicle_details',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดรถเพิ่มเติม'),
        ),
    ]
